### ISSUE TITLE
Scripts in package.json

### ISSUE THREAD

**Issue by CampbellDocherty** [fac20/week5-FHIN#23]
- You can add a script in your package.json scripts section --- "dev": "nodemon server.js" (where server.js is the path to your server file)

- Now you can run 'npm run dev' in your terminal and nodemon will run your server and refresh when changes are made to your files - this will save you having to restart your server every time with 'node server.js'

**Comment by khadija-nur** [comment]
You can also just write nodemon and it should work..as long as you've specified your path in the main section of your package.json

![Screenshot from 2020-08-14 10-45-32](https://user-images.githubusercontent.com/59174800/90237173-c17e8900-de1b-11ea-96ef-3911955751f0.png)
![Screenshot from 2020-08-14 10-50-09](https://user-images.githubusercontent.com/59174800/90237311-ff7bad00-de1b-11ea-9d34-b2310e5df4a2.png)
